/* eslint-disable */
// Auto-generated by scripts/generate-route-registry.mjs — do not edit manually.

export type RouteEntry = {
  segments: string[]
  importPath: string
}

export const ROUTE_ENTRIES: RouteEntry[] = [
  {
    segments: ["account","api-keys",":id"],
    importPath: 'routes/account/api-keys/[id]/route',
  },
  {
    segments: ["account","api-keys"],
    importPath: 'routes/account/api-keys/route',
  },
  {
    segments: ["account","invitations",":id"],
    importPath: 'routes/account/invitations/[id]/route',
  },
  {
    segments: ["account","invitations"],
    importPath: 'routes/account/invitations/route',
  },
  {
    segments: ["account","members",":userId"],
    importPath: 'routes/account/members/[userId]/route',
  },
  {
    segments: ["account","members"],
    importPath: 'routes/account/members/route',
  },
  {
    segments: ["account","overview"],
    importPath: 'routes/account/overview/route',
  },
  {
    segments: ["account","roles",":id"],
    importPath: 'routes/account/roles/[id]/route',
  },
  {
    segments: ["account","roles"],
    importPath: 'routes/account/roles/route',
  },
  {
    segments: ["account"],
    importPath: 'routes/account/route',
  },
  {
    segments: ["account","transfer-ownership"],
    importPath: 'routes/account/transfer-ownership/route',
  },
  {
    segments: ["ai","autoreply",":conversationId"],
    importPath: 'routes/ai/autoreply/[conversationId]/route',
  },
  {
    segments: ["ai","config"],
    importPath: 'routes/ai/config/route',
  },
  {
    segments: ["ai","draft"],
    importPath: 'routes/ai/draft/route',
  },
  {
    segments: ["ai","knowledge",":id"],
    importPath: 'routes/ai/knowledge/[id]/route',
  },
  {
    segments: ["ai","knowledge","reindex"],
    importPath: 'routes/ai/knowledge/reindex/route',
  },
  {
    segments: ["ai","knowledge"],
    importPath: 'routes/ai/knowledge/route',
  },
  {
    segments: ["ai","playground"],
    importPath: 'routes/ai/playground/route',
  },
  {
    segments: ["ai","test"],
    importPath: 'routes/ai/test/route',
  },
  {
    segments: ["ai","usage"],
    importPath: 'routes/ai/usage/route',
  },
  {
    segments: ["automations",":id","duplicate"],
    importPath: 'routes/automations/[id]/duplicate/route',
  },
  {
    segments: ["automations",":id","logs"],
    importPath: 'routes/automations/[id]/logs/route',
  },
  {
    segments: ["automations",":id"],
    importPath: 'routes/automations/[id]/route',
  },
  {
    segments: ["automations","cron"],
    importPath: 'routes/automations/cron/route',
  },
  {
    segments: ["automations","engine"],
    importPath: 'routes/automations/engine/route',
  },
  {
    segments: ["automations"],
    importPath: 'routes/automations/route',
  },
  {
    segments: ["automations","templates"],
    importPath: 'routes/automations/templates/route',
  },
  {
    segments: ["broadcasts",":id"],
    importPath: 'routes/broadcasts/[id]/route',
  },
  {
    segments: ["broadcasts"],
    importPath: 'routes/broadcasts/route',
  },
  {
    segments: ["contacts",":id"],
    importPath: 'routes/contacts/[id]/route',
  },
  {
    segments: ["contacts"],
    importPath: 'routes/contacts/route',
  },
  {
    segments: ["custom-fields",":id"],
    importPath: 'routes/custom-fields/[id]/route',
  },
  {
    segments: ["custom-fields"],
    importPath: 'routes/custom-fields/route',
  },
  {
    segments: ["dashboard"],
    importPath: 'routes/dashboard/route',
  },
  {
    segments: ["deals",":id"],
    importPath: 'routes/deals/[id]/route',
  },
  {
    segments: ["deals"],
    importPath: 'routes/deals/route',
  },
  {
    segments: ["flows",":id","activate"],
    importPath: 'routes/flows/[id]/activate/route',
  },
  {
    segments: ["flows",":id"],
    importPath: 'routes/flows/[id]/route',
  },
  {
    segments: ["flows",":id","runs"],
    importPath: 'routes/flows/[id]/runs/route',
  },
  {
    segments: ["flows","cron"],
    importPath: 'routes/flows/cron/route',
  },
  {
    segments: ["flows"],
    importPath: 'routes/flows/route',
  },
  {
    segments: ["flows","templates"],
    importPath: 'routes/flows/templates/route',
  },
  {
    segments: ["inbox","conversations",":id","read"],
    importPath: 'routes/inbox/conversations/[id]/read/route',
  },
  {
    segments: ["inbox","conversations"],
    importPath: 'routes/inbox/conversations/route',
  },
  {
    segments: ["inbox","messages"],
    importPath: 'routes/inbox/messages/route',
  },
  {
    segments: ["invitations",":token","peek"],
    importPath: 'routes/invitations/[token]/peek/route',
  },
  {
    segments: ["invitations",":token","redeem"],
    importPath: 'routes/invitations/[token]/redeem/route',
  },
  {
    segments: ["me","password"],
    importPath: 'routes/me/password/route',
  },
  {
    segments: ["me"],
    importPath: 'routes/me/route',
  },
  {
    segments: ["me","sessions"],
    importPath: 'routes/me/sessions/route',
  },
  {
    segments: ["message-templates"],
    importPath: 'routes/message-templates/route',
  },
  {
    segments: ["notifications"],
    importPath: 'routes/notifications/route',
  },
  {
    segments: ["notifications","unread-count"],
    importPath: 'routes/notifications/unread-count/route',
  },
  {
    segments: ["pipelines",":id"],
    importPath: 'routes/pipelines/[id]/route',
  },
  {
    segments: ["pipelines"],
    importPath: 'routes/pipelines/route',
  },
  {
    segments: ["presence"],
    importPath: 'routes/presence/route',
  },
  {
    segments: ["quick-replies",":id"],
    importPath: 'routes/quick-replies/[id]/route',
  },
  {
    segments: ["quick-replies"],
    importPath: 'routes/quick-replies/route',
  },
  {
    segments: ["realtime","stream"],
    importPath: 'routes/realtime/stream/route',
  },
  {
    segments: ["storage","upload"],
    importPath: 'routes/storage/upload/route',
  },
  {
    segments: ["tags",":id"],
    importPath: 'routes/tags/[id]/route',
  },
  {
    segments: ["tags"],
    importPath: 'routes/tags/route',
  },
  {
    segments: ["v1","broadcasts",":id"],
    importPath: 'routes/v1/broadcasts/[id]/route',
  },
  {
    segments: ["v1","broadcasts"],
    importPath: 'routes/v1/broadcasts/route',
  },
  {
    segments: ["v1","contacts",":id"],
    importPath: 'routes/v1/contacts/[id]/route',
  },
  {
    segments: ["v1","contacts"],
    importPath: 'routes/v1/contacts/route',
  },
  {
    segments: ["v1","conversations",":id","messages"],
    importPath: 'routes/v1/conversations/[id]/messages/route',
  },
  {
    segments: ["v1","conversations",":id"],
    importPath: 'routes/v1/conversations/[id]/route',
  },
  {
    segments: ["v1","conversations"],
    importPath: 'routes/v1/conversations/route',
  },
  {
    segments: ["v1","me"],
    importPath: 'routes/v1/me/route',
  },
  {
    segments: ["v1","messages"],
    importPath: 'routes/v1/messages/route',
  },
  {
    segments: ["v1","webhooks",":id"],
    importPath: 'routes/v1/webhooks/[id]/route',
  },
  {
    segments: ["v1","webhooks"],
    importPath: 'routes/v1/webhooks/route',
  },
  {
    segments: ["whatsapp","broadcast"],
    importPath: 'routes/whatsapp/broadcast/route',
  },
  {
    segments: ["whatsapp","config"],
    importPath: 'routes/whatsapp/config/route',
  },
  {
    segments: ["whatsapp","config","verify-registration"],
    importPath: 'routes/whatsapp/config/verify-registration/route',
  },
  {
    segments: ["whatsapp","media",":mediaId"],
    importPath: 'routes/whatsapp/media/[mediaId]/route',
  },
  {
    segments: ["whatsapp","react"],
    importPath: 'routes/whatsapp/react/route',
  },
  {
    segments: ["whatsapp","send"],
    importPath: 'routes/whatsapp/send/route',
  },
  {
    segments: ["whatsapp","session"],
    importPath: 'routes/whatsapp/session/route',
  },
  {
    segments: ["whatsapp","sync"],
    importPath: 'routes/whatsapp/sync/route',
  },
  {
    segments: ["whatsapp","templates",":id"],
    importPath: 'routes/whatsapp/templates/[id]/route',
  },
  {
    segments: ["whatsapp","templates","submit"],
    importPath: 'routes/whatsapp/templates/submit/route',
  },
  {
    segments: ["whatsapp","templates","sync"],
    importPath: 'routes/whatsapp/templates/sync/route',
  },
  {
    segments: ["whatsapp","webhook"],
    importPath: 'routes/whatsapp/webhook/route',
  }
]
